export default [
["zoom: 'close', hud: 'full', filter: 'none'", "zoom: 'close', hud: 'minimal', hudV2: 1, filter: 'none'"],
["Object.assign(SET, o); delete SET.combat;", "Object.assign(SET, o); delete SET.combat; if (!o.hudV2) SET.hud = 'minimal'; SET.hudV2 = 1; if (!['bar', 'pct', 'num'].includes(SET.bossHp)) SET.bossHp = SET.bossHp === 'both' ? 'num' : 'bar';   /* HUD-SLIM (Daniel 10-09): MINIMAL is the default, and a settings file from before it takes it ONCE (hudV2): the plate HUD is an opt-in you keep once you pick it. The old BAR+BOTH boss readout is NUMBERS now. */"],
["k === 'HUD' ? SET.hud.toUpperCase() :", "k === 'HUD' ? (SET.hud === 'full' ? 'PLATE' : 'MINIMAL') :"],
["const hpLift = () => (SET.bossHp === 'pct' || SET.bossHp === 'num' || SET.bossHp === 'both' ? 10 : 0);", "const hpLift = () => 0;"],
["const BOSSHP_MODES = ['bar', 'pct', 'num', 'both'], BOSSHP_LABEL = { bar: 'BAR', pct: 'BAR+%', num: 'BAR+NUMBERS', both: 'BAR+BOTH' };", "const BOSSHP_MODES = ['bar', 'pct', 'num'], BOSSHP_LABEL = { bar: 'BAR', pct: 'BAR+%', num: 'BAR+NUMBERS' };   /* ONE readout per choice, beside the one bar: nothing, the %, or the numbers (the old triple of name, numbers+% and bar is gone) */"],
["return m === 'pct' ? p : m === 'num' ? n : n + ' ' + p; }", "return m === 'pct' ? p : n; }"],
["if (t) text(t, VW / 2, VH - 21, '#fff6e0', 'center', 8); }", "if (t) text(t, VW / 2 + 64, hpBy() - 1, '#fff6e0', 'left', 8); }"],
["bh = Math.round(VH * 0.11 * k); g.fillStyle = '#0a0810'; g.fillRect(0, 0, VW, bh); g.fillRect(0, VH - bh, VW, bh); const nm = miniIntroT > 0 ? miniName() : bossTitle(boss); if (k >= 1) { const z = fitSize(nm, Math.min(VW, 320) - 16, [TYPE.title, 8]); g.fillStyle = 'rgba(10,8,16,0.66)'; g.fillRect(0, VH / 2 - 12, VW, (z >= 12 ? 16 : 8) + 12); text(nm, VW / 2, VH / 2 - 6, '#ffd36b', 'center', z, 'outline'); } }",
 "bh = Math.round(VH * 0.13 * k); g.fillStyle = '#0a0810'; g.fillRect(0, 0, VW, bh); g.fillRect(0, VH - bh, VW, bh); const nm = miniIntroT > 0 ? miniName() : bossTitle(boss); if (k >= 1) { const z = fitSize(nm, Math.min(VW, 320) - 16, [TYPE.title, 8]); text(nm, VW / 2, Math.round((bh - (z >= 12 ? 16 : 8)) / 2), '#ffd36b', 'center', z, 'outline'); } }   /* THE NAME CARD lives in the TOP band (the top fifth), never across the middle: it used to cover the boss's head */"],
["const textRec = (kind, o) => { const r = window.__textRec; if (!r || r.length > 20000) return;", "const NULLG = (() => { const c = document.createElement('canvas'); c.width = c.height = 1; return c.getContext('2d'); })();   /* where the idle MINIMAL HUD draws what is not shown (the HUD code runs once, the screen sees nothing) */\nconst textRec = (kind, o) => { const r = window.__textRec; if (!r || r.length > 20000 || g === NULLG) return;"],
["function hudMeterLabel() {", "function heroMeterFrac() { return ((hero() === 'knight' ? (lcOn() ? 100 : P.resolve) : isPyro() ? P.heat : isPaladin() ? P.light : isWarden() ? P.vigil : isGeo() ? P.tremor : isReaper() ? P.harvest : isPirate() ? P.plunder : 0) || 0) / 100; }   /* the fill of the hero's own meter, 0-1 (the idle MINIMAL HUD wakes for it) */\nfunction hudMeterLabel() {"],
["    bolt: outline(fromGrid(['..gg.', '.gg..', 'gggg.', '..gg.', '.gg..'], { g: '#8fd160' }, 1), ART.OUT),", "    bolt: outline(fromGrid(['..gg.', '.gg..', 'gggg.', '..gg.', '.gg..'], { g: '#8fd160' }, 1), ART.OUT),\n    hudBolt: outline(fromGrid(['...gg', '..gg.', '.gggg', '..gg.', '.gg..', '.g...'], { g: '#8fd160' }, 1), ART.OUT),   /* THE HUD ICONS: one pixel scale, one cell (7-9 wide, 8 tall): heart, bolt, flask */\n    hudFlask: outline(fromGrid(['..c..', '..c..', '.rrr.', 'rrrrr', 'rLrrr', '.rrr.'], { c: '#c9d1dc', r: '#c9463d', L: '#ff9a9a' }, 1), ART.OUT),"],
// the caravan's status rows: down two, and on a strip
["const x = 22, y = 50, k = v >= 1 ? 3 : v >= SUN.swimAt ? 2 : v > 0.2 ? 1 : 0;\n  g.drawImage(A.ui.sun[k], x - 14, y - 3);", "const x = 22, y = 52, k = v >= 1 ? 3 : v >= SUN.swimAt ? 2 : v > 0.2 ? 1 : 0;\n  { const strip = (sx, sy, sw, sh) => { g.fillStyle = 'rgba(10,8,20,0.55)'; g.beginPath(); g.roundRect(sx, sy, sw, sh, 2); g.fill(); hudRects.push([sx, sy, sw, sh]); };   /* THE STATUS ROWS sit on a strip, not on the picture */\n    strip(2, y - 5, 98, 15); if ((WTH && WTH.on()) || (RGH && RGH.on())) strip(2, y + 10, 74, 14); }\n  g.drawImage(A.ui.sun[k], x - 14, y - 3);"],
];
