import { patch } from './patch.mjs';
patch('work/claude/lane-done/claude-lance.md', [
  ["- **The held Stormhold rebuild.** `claude/stormhold` moves the bridge to 544 in `src/stormhold-town.js`. It does not",
   "- **The held Stormhold rebuild.** `claude/stormhold` moves the bridge to 544, in its stormhold-town module. It does not"],
  ["| (this) | this report |",
   "| a4224a6 | this report |\n| (next) | Daniel's answers: the three fire archers removed, THE QUEEN'S BOWS added to the move words, this report updated |"],
  ["## QUESTIONS FOR DANIEL",
   "## DANIEL'S ANSWERS (2026-09-25: \"recs fine, remove the fire archers\")\n\n1. **Done.** The three fire archers on the bridge (322, 358, 412) are gone from `stormhold()`. The rock goblin at 394\n   stays. Static checks pass (below).\n2. Nearer lookout: kept as built.\n3. 15 s with at most 2: no change. He plays it first, and it goes to 20 s if it feels busy.\n4. **Done in code.** \"THE QUEEN'S BOWS\" is in `MOVE_WORDS`, so the arrival tell now shows it as floating text over the\n   lookout. **Not yet seen in the page:** textfit, tells and a capture wait for the machine to be free.\n5. **Stormhold port: to be done in the same batch when `claude/stormhold` ships.** Add one\n   `lanceLookouts({ plat, ent }, P0, BY)` call in that branch's bridge builder and put `bows:` on its arena. Also drop\n   that branch's copies of the three fire archers.\n6. No tuning.\n\n**Checks after the removal (static only; the coordinator held the browser checks because of load):** syntax, spawns,\none-new-foe, elites, audit, content-audit, comments, homepaths, dangling-paths, floaters, architecture, traps,\nkillzones, deadends, signs, keys, arena-supplies and checkpoints all pass. **Still to run when the machine is free:**\ntextfit, tells, boss-openings, boss-fight-end, lance-support, the captures, and the re-pilot.\n\n**The pilot numbers above should not move with the removal.** The boss lab kills every non-boss foe before the fight,\nso the fire archers were never in any pilot row. The re-pilot is pending anyway, to confirm that.\n\n## QUESTIONS FOR DANIEL (answered, see above)"],
]);
