import { patch } from './patch.mjs';
patch('work/claude/lane-done/claude-lance.md', [
  ["| (next) | Daniel's answers: the three fire archers removed, THE QUEEN'S BOWS added to the move words, this report updated |",
   "| f9b4463 | Daniel's answers: the three fire archers removed, THE QUEEN'S BOWS added to the move words |\n| a407d2d | merge origin/master ab26448 (check.mjs: every name from both sides kept - `tower-collapse`, `sexton` and `lance-support`; spawn line verified; POISE_SKIP still starts with the Winchmaster) |\n| (this) | the words placed on the screen, final checks, re-pilot, captures, report |"],
  ["4. **Done in code.** \"THE QUEEN'S BOWS\" is in `MOVE_WORDS`, so the arrival tell now shows it as floating text over the\n   lookout. **Not yet seen in the page:** textfit, tells and a capture wait for the machine to be free.",
   "4. **Done.** \"THE QUEEN'S BOWS\" is in `MOVE_WORDS` and shows as floating text when the call is made. The captures\n   showed two problems, both fixed: over the west lookout the words were clipped at the screen's left edge, and with\n   the lookout off the screen the words landed out of view. They now sit over the lookout, or at the screen edge\n   nearest it, clamped by their own `textW` width (`work/lance/after-04-bowman-called.png`, `after-06-bowman-called-offscreen.png`)."],
  ["**Checks after the removal (static only; the coordinator held the browser checks because of load):** syntax, spawns,\none-new-foe, elites, audit, content-audit, comments, homepaths, dangling-paths, floaters, architecture, traps,\nkillzones, deadends, signs, keys, arena-supplies and checkpoints all pass. **Still to run when the machine is free:**\ntextfit, tells, boss-openings, boss-fight-end, lance-support, the captures, and the re-pilot.\n\n**The pilot numbers above should not move with the removal.** The boss lab kills every non-boss foe before the fight,\nso the fire archers were never in any pilot row. The re-pilot is pending anyway, to confirm that.",
   "**Final checks, after the merge with ab26448:** 29 of 29 named checks pass. That is: boss-openings, boss-fight-end,\narena-supplies, tells, one-new-foe, elites, spawns, floaters, architecture, audit, content-audit, traps, killzones,\ndeadends, signs, textfit, comments, syntax, homepaths, dangling-paths, watchtowers, keys, bridge-props, checkpoints,\ncheckpoint-gaps, small-adds, runtime-footing, lance-support, and ore-road (A8). After the word-placement edit, syntax,\ncomments, tells, lance-support and textfit were run again and pass.\n\n**Final re-pilot** (all 7 heroes, same settings, `work/lance/pilot-final.json`):\n\n| | before | after (final) |\n|---|---|---|\n| refill wins | 8/14 | **12/14** (knight times out at 11%) |\n| refill median win | 131.7 s | **111.8 s** |\n| refill median damage taken | 429 | **312** |\n| normal-health wins | 0/7 | 0/7 (13-84 s) |\n\nEvery row matches the earlier after-run except the reaper's (96.5 s and 252 damage, was 100 s and 276), and his is\nthe one row that draws dice. That is expected: the boss lab removes every non-boss foe before it fights, so the fire\narchers were never in any pilot row. **The removal changes a player's fight, not the bot's.**"],
]);
