import { patch } from './patch.mjs';
patch('src/main.js', [
  ["import {bakeBellcrab,bakeBellguard} from './bellcrab.js';", "import {bakeBellcrab,bakeBellguard} from './bellcrab.js';\nimport { lanceSupport, LANCE_SUPPORT } from './lance-support.js';   /* THE QUEEN'S BOWS: the archers he calls to the end lookouts (docs/briefs/lance-support.md) */"],
  ["  e.vy += 1000 * dt; if (e.vy > 340) e.vy = 340;\n  const d = P.x - e.x, ad = Math.abs(d), p2 = e.phase === 2;",
   "  e.vy += 1000 * dt; if (e.vy > 340) e.vy = 340;\n  /* THE QUEEN'S BOWS (Daniel, 2026-09-25: \"occasional archer support since he lacks ranged moves\"): every 15 s a horn on a\n     tower, and a plain archer drops onto the end lookout nearer you. Not in the Boss Rush, which is parked: nothing new goes in it */\n  if (bossActive && e.alive && e.mode !== 'sleep' && e.mode !== 'wake' && !rushOn()) lanceSupport(e, dt, lanceIO(A));\n  const d = P.x - e.x, ad = Math.abs(d), p2 = e.phase === 2;"],
  ["const lanceOpen = e => e.mode === 'planted' ||",
   "/* what lanceSupport (src/lance-support.js) is allowed to touch: the call is TOLD (C1) - the horn, THE QUEEN'S BOWS over the lookout\n   and a column of amber sparks on it for LANCE_SUPPORT.tell - and then the bowman drops onto it off the tower roof */\nconst lanceIO = A => ({ P, TS, lookouts: A.bows, bows: () => enemies.filter(q => q.alive && q.lanceBow),\n  announce: c => { number(c.x, c.y - 30, \"THE QUEEN'S BOWS\", '#ffd36b'); SFX.hornDraw(); },\n  tellFx: (c, dt) => { if (Math.random() < dt * 45) parts.push({ x: c.x + (Math.random() - 0.5) * 70, y: c.y - Math.random() * 4, vx: 0, vy: -50 - Math.random() * 50, life: 0.5, max: 0.5, col: Math.random() < 0.5 ? '#ffd36b' : '#ff9a5c', size: 1, grav: 0 }); },\n  arrive: c => { const n0 = enemies.length; spawnEnt({ t: 'archer', x: c.tx, y: c.row - 1, face: Math.sign(P.x - c.x) || 1 });\n    for (let i = n0; i < enemies.length; i++) { const q = enemies[i]; q.lanceBow = true; q.seenP = true; q.woke = 1; q.sleeper = false; q.y -= LANCE_SUPPORT.drop; q.vy = 0; q.timer = LANCE_SUPPORT.quiet; }\n    dust(c.x, c.y, 10); smoke(c.x, c.y - LANCE_SUPPORT.drop, 4, 10); SFX.leap(); SFX.thud(); } });\nconst lanceOpen = e => e.mode === 'planted' ||"],
  ["      for (const dd of [-1, 1]) waves.push({ x: x + dd * 20, y: floor, dir: dd, life: 2.4, sp: 200 });\n      SFX.bellow(); SFX.heavy(); SFX.crack(); say('THE BRIDGE IS YOURS', '#ffd36b'); break; }",
   "      for (const dd of [-1, 1]) waves.push({ x: x + dd * 20, y: floor, dir: dd, life: 2.4, sp: 200 });\n      for (const q of enemies) if (q.alive && q.lanceBow) { q.alive = false; smoke(q.x, q.y - 6, 6, 8); }   /* his bowmen throw down their bows and are gone */\n      e.bowCall = null;\n      SFX.bellow(); SFX.heavy(); SFX.crack(); say('THE BRIDGE IS YOURS', '#ffd36b'); break; }"],
  ["His thrust can be parried; the low sweep cannot, so jump it. His charges take the deck out behind him. Half dead",
   "His thrust can be parried; the low sweep cannot, so jump it. When a horn goes on a tower, one of HER bowmen is coming down onto an end lookout: he is only an archer, so cut him down. Half dead"],
]);
