require('./rep.cjs')('src/main.js', rep => {
// the old store line leaves the SMITH: it is EXTRA FLASK I on the FLASKS tab (same id, same price)
rep("  /* (claude/survival, Daniel 10-07: the tonic is a FLASK you drink, src/survival.js) the store line is one more flask a shrine fills, two at most: PROG.flaskUp. The id stays 'tonic' for old saves and the golden stock */\n  { id: 'tonic', name: 'EXTRA FLASK', price: 150, consumable: true, max: 2, desc: 'one more red flask to carry. you start with one; the smith can make it three. a shrine gives one back, a death all.' },   /* (survival2, A10b: base 1, max 3; a save that bought them keeps them, one for one - no refund, each still +1) */\n",
  "  /* (claude/flasks2, Daniel 10-08) THE EXTRA FLASK line moved to the store's own FLASKS tab (FLASK_ROWS): EXTRA FLASK I keeps the id 'tonic' and its 150 gold */\n");
rep("{ id: 'smith', name: 'SMITH', items: UPGRADES, key: null, owned: 'items' }", "{ id: 'smith', name: 'SMITH', items: UPGRADES, key: null, owned: 'items' }, { id: 'flasks', name: 'FLASKS', items: FLASK_ROWS, key: null, owned: 'flaskItems', flasks: true }");
rep("const STORE_TABS = [", "/* THE FLASKS TAB (claude/flasks2, src/flasks2.js): COUNT, POTENCY, PERKS. A line's gate is a feat 'flask:<id>' (featDone asks src/flasks2.js reqDone);\n   a HIDDEN line not yet found is '???' (storeItems) */\nconst FLASK_ROWS = F2.FLASK_ITEMS.map(k => ({ ...k, desc: k.group + ': ' + k.desc, ...(k.req ? { feat: 'flask:' + k.id, featName: k.hidden ? 'find something hidden out in the woods' : k.req.name } : {}) }));\nconst STORE_TABS = [");
rep("const storeItems = tab => (tab.key === 'charm' ? [NO_CHARM].concat(tab.items) : tab.items).filter(k => !k.hero || k.hero === hero());",
  "const storeItems = tab => tab.flasks ? tab.items.map(k => F2.shownAsHidden(k, PROG) && !godMode() ? { ...k, name: '???', desc: k.group + ': ???', hiddenRow: true } : k) : (tab.key === 'charm' ? [NO_CHARM].concat(tab.items) : tab.items).filter(k => !k.hero || k.hero === hero());");
rep("const featDone = f => String(f).startsWith('boss:')", "const featDone = f => String(f).startsWith('flask:') ? F2.reqDone(F2.itemOf(String(f).slice(6)), PROG) : String(f).startsWith('boss:')");
// buying a flask line
rep("    else if (k.silver && coinRoute(k) && PROG.coins >= k.coinPrice) {",
  "    else if (tab.flasks) { if (godMode() || PROG.coins >= k.price) { if (!godMode()) PROG.coins -= k.price; PROG.flaskItems = PROG.flaskItems || {}; PROG.flaskItems[k.id] = true; PROG.flaskUp = F2.countOf(PROG); if (k.count) { P.flasks = (P.flasks | 0) + 1; flaskHud.flashT = 0.8; } saveProgress(); SFX.coin(); SFX.sting(); storeMsg = 'bought ' + k.name + (k.count ? ': ' + SV.flaskMax(PROG) + ' FLASKS' : ''); storeMsgT = 2.5; } else { SFX.buzz(); storeMsg = 'need ' + (k.price - PROG.coins) + ' more gold'; storeMsgT = 2; } }   /* (claude/flasks2) a count line is one more flask at once */\n    else if (k.silver && coinRoute(k) && PROG.coins >= k.coinPrice) {");
rep("    : k.practice ? PORTAL_ICON : k.id === 'tonic' ? TONIC_ICON :", "    : k.practice ? PORTAL_ICON : tab.flasks ? (k.hiddenRow ? PROP.flaskIcons.hidden : k.count ? TONIC_ICON : PROP.flaskIcons[k.id] || TONIC_ICON) : k.id === 'tonic' ? TONIC_ICON :");
});
