require('./rep.cjs')('src/main.js', rep => {
// SHRINE BLESSING: a shrine gives back two
rep("for (const p of players) p.flasks = SV.shrineRefill(p.flasks, fm);", "const give = F2.shrineGives(PROG); for (const p of players) { const was = p.flasks | 0; for (let i = 0; i < give; i++) p.flasks = SV.shrineRefill(p.flasks, fm); if (p === P && (p.flasks | 0) > was) flaskHud.flashT = 0.8; }   /* (claude/flasks2) SHRINE BLESSING gives back two */");
// break 5 shrines (never in God Mode)
rep("number(s.x, s.y - 44, 'SHRINE BROKEN  +1 FLASK', '#ff9a5c'); hintT = 4; hintMsg = SV.LINES.broken; }",
  "number(s.x, s.y - 44, 'SHRINE BROKEN  +1 FLASK', '#ff9a5c'); hintT = 4; hintMsg = SV.LINES.broken; flaskHud.flashT = 0.8;\n  if (F2.objShrineBroken(PROG, { assist: assistOn() }).length) { saveProgress(); flaskObjSay('shrines5'); } }   /* (claude/flasks2) SHRINE BLESSING's objective: break five */\nconst assistOn = () => !!(SET.invincible || SET.godmode);   /* THE ASSIST GUARD: God Mode / Unlock All earn no flask objective */\nfunction flaskObjSay(id) { SFX.medal(); toastNow(F2.OBJ_LINE[id], 5); }\nfunction toastNow(msg, t) { hintMsg = msg; hintT = t; }");
// a dry clear (QUICK DRAUGHT's objective)
rep("  PROG.coins = (PROG.coins || 0) + got; earned = got;", "  PROG.coins = (PROG.coins || 0) + got; earned = got;\n  if (F2.objLevelCleared(PROG, { drinks: flaskHud.levelDrinks, assist: assistOn(), real: !LEVELS[levelIndex].hidden || !!LEVELS[levelIndex].secret }).length) setTimeout(() => SFX.medal(), 1400), PROG.flaskObjNew = 'dry';   /* (claude/flasks2) a wood cleared without a drink opens QUICK DRAUGHT (said on the win card) */");
// a new run of a wood: no drinks yet
rep("  for (const s of shrines) { s.broken = false; s.life = -1; } respawn(); P.flasks = SV.flaskMax(PROG);", "  for (const s of shrines) { s.broken = false; s.life = -1; } respawn(); P.flasks = SV.flaskMax(PROG); flaskHud.levelDrinks = 0; flaskHud.spills = []; flaskHud.glowT = 0;");
// THE HIDDEN FINDS, placed at load (no level hash moves)
rep("  acorns = []; signs = []; shrines = []; gate = null; total = 0; silvers = [];\n  for (const e of L.ents) {\n    const px = e.x * TS + 8, py = (e.y + 1) * TS;\n    if (e.t === 'coin') { acorns.push({ x: px, y: py - 6, got: false, ph: Math.random() * 6 }); total++; }",
  "  acorns = []; signs = []; shrines = []; gate = null; total = 0; silvers = [];\n  flaskFinds = F2.findsIn(LEVELS[i] && LEVELS[i].id, PROG).map(f => ({ ...f, px: f.x * TS + 8, py: (f.y + 1) * TS - 6, got: false }));   /* (claude/flasks2) the hidden flask finds of this wood (src/flasks2.js FINDS) */\n  for (const e of L.ents) {\n    const px = e.x * TS + 8, py = (e.y + 1) * TS;\n    if (e.t === 'coin') { acorns.push({ x: px, y: py - 6, got: false, ph: Math.random() * 6 }); total++; }");
rep("let silvers = []; // the three silver coins of the level: { x, y, i, got }", "let silvers = []; // the three silver coins of the level: { x, y, i, got }\nlet flaskFinds = [];   /* (claude/flasks2) a hidden flask find in this wood: { id, px, py, got } - picked up once a save (PROG.flaskFinds) */");
rep("  for (const s of silvers) if (!s.got && !P.dead && !SET.invincible && Math.abs(s.x - P.x) < 13",
  "  for (const f of flaskFinds) if (!f.got && !P.dead && Math.abs(f.px - P.x) < 13 && Math.abs(f.py - (P.y - 7)) < 15) { f.got = true; PROG.flaskFinds = PROG.flaskFinds || {}; PROG.flaskFinds[f.id] = true; saveProgress(); SFX.medal(); SFX.sting(); number(f.px, f.py - 18, f.name, '#ffd36b'); burst(f.px, f.py, 14, ['#ffd36b', '#fff6c8', '#ff9a9a'], 60, 0.6, -30, 1); ringAt(f.px, f.py, 22, '#ffd36b', 0.45); toastNow(f.line, 6); }   /* (claude/flasks2) A HIDDEN FIND: its line opens on the FLASKS tab */\n  for (const s of silvers) if (!s.got && !P.dead && !SET.invincible && Math.abs(s.x - P.x) < 13");
rep("  for (const s of silvers) if (s.x > cx - 12 && s.x < cx + VW + 12) {", "  for (const f of flaskFinds) if (!f.got && f.px > cx - 12 && f.px < cx + VW + 12) { const bob = Math.round(Math.sin(time * 3 + f.px) * 2), x = Math.round(f.px - cx), y = Math.round(f.py - cy) + bob; g.globalAlpha = 0.25 + 0.15 * Math.sin(time * 5); g.fillStyle = '#ffd36b'; g.beginPath(); g.arc(x, y, 7, 0, 7); g.fill(); g.globalAlpha = 1;\n    g.drawImage(f.id === 'sunlight' ? PROP.flaskIcons.sunlight : f.id === 'steady' ? PROP.flaskIcons.steady : PROP.hudFlaskGold, x - 3, y - 4); if (Math.floor(time * 4 + f.px) % 5 === 0) { g.fillStyle = '#fff6c8'; g.fillRect(x + 3, y - 5, 1, 1); } }   /* (claude/flasks2) a hidden flask find: a gold glint, bobbing */\n  for (const s of silvers) if (s.x > cx - 12 && s.x < cx + VW + 12) {");
});
