import assert from 'node:assert/strict';import{openPage}from'./cdp.mjs';
const pg=await openPage({audio:false,fonts:false});try{
 const r=await pg.evalp(`(async()=>{const{LEVELS}=await import('/src/level.js');BK.manualSimulation=true;BK.SET.speed=1;const out=[];
 for(const h of ['knight','warden','pyro','paladin','pirate','reaper']){BK.setHero(h);BK.reset({fresh:true});BK.load(LEVELS.findIndex(l=>l.id==='burial'));BK.state='play';BK.god=false;for(const e of BK.enemies())e.alive=false;const p=BK.P;
  const jump=target=>{BK.press('jump');BK.keys.jump=true;let air=false,land=false;for(let f=0;f<150;f++){BK.keys.right=p.x<target-2;BK.keys.left=p.x>target+2;BK.sim(1);if(!p.ground)air=true;if(air&&p.ground){land=true;break;}}for(const k in BK.keys)BK.keys[k]=false;if(!land||p.dead)throw Error(h+' failed jump');BK.sim(3);};
  BK.tp(407,31);BK.sim(8);jump(411*16+8);for(let x=412;x<=437;x+=5){while(p.x<x*16+8){BK.keys.right=true;BK.sim(1);}BK.keys.right=false;jump((x+4)*16+8);if(p.y>32*16)throw Error(h+' poison crossing fell');}jump(445*16+8);
  BK.tp(862,31);BK.sim(8);for(let step=0;step<4;step++){jump((864+step)*16+8);if(Math.abs(p.y-(30-step*2)*16)>1)throw Error(h+' bone stair '+step+' y='+p.y);}
  out.push({h,graveCrossing:true,boneStairs:true,alive:!p.dead});}
 BK.god=true;BK.tp(625,31);const rock=BK.props().find(p=>p.t==='stal'&&Math.abs(p.x-625*16-8)<5),rockStates=new Set();for(let f=0;f<100;f++){BK.sim(1);rockStates.add(rock.state);}if(!rockStates.has('shake')||!rockStates.has('gone'))throw Error('falling stone did not warn and drop');
 BK.reset({fresh:true});BK.load(LEVELS.findIndex(l=>l.id==='burial'));BK.state='play';BK.god=true;const distant=BK.enemies().find(e=>e.t==='zombie'&&e.mode==='walk'&&e.x>900*16);if(!distant)throw Error('missing distant zombie');const homeX=distant.x;BK.sim(120);if(!distant.alive||distant.x!==homeX)throw Error('distant zombie left encounter');BK.tp((homeX-70)/16,(distant.y-1)/16);BK.sim(30);if(distant.x===homeX)throw Error('nearby zombie did not activate');
 BK.reset({fresh:true});BK.load(LEVELS.findIndex(l=>l.id==='burial'));BK.state='play';BK.god=true;const A=BK.L.arena;BK.tp(A.trigger/16+1,31);BK.sim(200);const b=BK.boss;for(let n=0;n<5;n++){b.mode='callTell';b.modeT=0;BK.sim(1);}const adds=BK.enemies().filter(e=>e.alive&&e.graveAdd);if(adds.length!==3)throw Error('summon cap '+adds.length);b.mode='rest';BKT.hurtEnemy(b,99999,b.x-80,false);BK.sim(10);if(BK.enemies().some(e=>e.alive&&e.graveAdd))throw Error('adds survive death');return{out,distantZombieSleeps:true,nearbyZombieActivates:true,summonCap:adds.length,rockStates:[...rockStates]};})()`);assert.equal(r.out.length,6);assert.deepEqual(pg.errors,[]);console.log(JSON.stringify(r));
}finally{pg.close();}
