import assert from 'node:assert/strict';
import{LEGACY_NODES,SKILLS,HERO_IDS,migrateProgress,loadProgress,importProgress,exportProgress,buySkill,equipSkill,equipped,slotsAt,growthAt}from'../src/progression.js';
import{xpFloor}from'../src/xp.js';
const memory=()=>{const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k),m};};
assert.equal(LEGACY_NODES.length,181);assert.equal(new Set(LEGACY_NODES.map(n=>n.hero+'/'+n.id)).size,181);assert(LEGACY_NODES.every(n=>['baseline','growth','skill'].includes(n.destination)));
for(let version=1;version<=6;version++)for(const hero of HERO_IDS.filter(h=>LEGACY_NODES.some(n=>n.hero===h))){   /* a hero with no talent history (THE GEOMANCER, 2026-09-24) has no old save to migrate */
 const learned=LEGACY_NODES.filter(n=>n.hero===hero&&n.destination==='skill'&&n.active),talents=Object.fromEntries(learned.map(n=>[n.id,true]));
 const raw=JSON.stringify({hero,heroes:{[hero]:true},xpVersion:1,xp:{[hero]:xpFloor(12)},coins:83,silverSpent:3,items:{heart:true},done:{[hero]:{wood:1}},talentVersion:version,talents:{[hero]:talents},skill:learned[0].id,skill2:learned[1]?.id,skin:'tide',inventory:{token:1}});
 const r=migrateProgress(raw),p=r.progress;assert.equal(p.coins,383);assert.equal(r.receipt.points[hero],12);for(const n of learned)assert(p.skillOwned[hero][n.id]);assert.equal(p.loadouts[hero][0],hero==='reaper'?'summonSkeleton':learned[0].id);assert.equal(p.loadouts[hero].length,2);/* an old save keeps its first TWO: MAX_SLOTS */assert.deepEqual(p.inventory,{token:1});assert.deepEqual(p.items,{heart:true});assert.deepEqual(p.done,{[hero]:{wood:1}});assert.equal(p.xp[hero],xpFloor(12));
 const again=migrateProgress(JSON.stringify(p));assert.equal(again.changed,false);assert.deepEqual(again.progress,p);
 const db=memory();db.setItem('save',raw);const saved=loadProgress(db,'save',raw);assert.equal(db.getItem(saved.backup),raw);assert.equal(JSON.parse(db.getItem('save')).coins,383);assert.equal(loadProgress(db,'save',db.getItem('save')).changed,false);
 // Export/import preserves the new ownership and refund receipt; importing an old backup transforms its own source once.
 const db2=memory();importProgress(db2,'import',exportProgress(p));assert.deepEqual(JSON.parse(db2.getItem('import')),p);importProgress(db2,'import',raw);assert.equal(JSON.parse(db2.getItem('import')).coins,383);importProgress(db2,'import',db2.getItem('import'));assert.equal(JSON.parse(db2.getItem('import')).coins,383);assert.deepEqual(migrateProgress(JSON.stringify(p)).progress,p);
}
const cap=migrateProgress(JSON.stringify({xpVersion:1,xp:{knight:xpFloor(99)},coins:0,talents:{knight:{heavy:99}},ptsTotal:99,coopWant:{hero:'warden',level:99}}));assert.equal(cap.receipt.refund,750);assert.equal(cap.receipt.points.warden,0);assert(cap.receipt.warnings.length);
const old=migrateProgress(JSON.stringify({hero:'knight',wood:{cleared:true},coins:0}),['wood']);assert.equal(old.receipt.points.knight,1);
for(const raw of ['bad','null','[]','{"coins":-1}','{"xp":{"knight":null}}','{"talents":{"knight":[]}}','{"progressionVersion":100}']){const db=memory();db.setItem('save',raw);assert.throws(()=>loadProgress(db,'save',raw));assert.equal(db.getItem('save'),raw);}
{const db=memory(),raw='{"coins":9}';db.setItem('save',raw);const original=db.setItem;db.setItem=(k,v)=>{if(k.includes('before-progression'))throw Error('quota');original(k,v);};assert.throws(()=>loadProgress(db,'save',raw));assert.equal(db.getItem('save'),raw);}
{const db=memory(),raw='{"coins":9}';db.setItem('save',raw);const original=db.setItem;let fail=true;db.setItem=(k,v)=>{if(k==='save'&&fail){fail=false;throw Error('quota');}original(k,v);};assert.throws(()=>loadProgress(db,'save',raw));assert.equal(db.getItem('save'),raw);}
/* the shop sells ABILITIES only (hero-kits 1b): the cheapest knight ability, bought one level short and then at its level */
const p=migrateProgress(null).progress,n=SKILLS.filter(n=>n.hero==='knight'&&n.active).sort((a,b)=>a.level-b.level)[0],L=n.level;p.coins=1000;assert.equal(buySkill(p,'knight',n.id,L-1),'Requires level '+L);assert.equal(buySkill(p,'knight',n.id,L),null);assert.equal(p.coins,1000-n.price);assert.equal(buySkill(p,'knight',n.id,L),'Already owned');assert.equal(p.coins,1000-n.price);assert(equipSkill(p,'knight',n.id,0,L,false));assert.equal(equipSkill(p,'knight',n.id,0,L,true),null);assert.equal(equipped(p,'knight',L)[0],n.id);assert(equipSkill(p,'knight',n.id,2,L,true));assert.equal(equipSkill(p,'knight',n.id,2,8,true),'Slot is locked');assert.equal(equipSkill(p,'knight',n.id,2,20,true),'Slot is locked');assert.equal(equipSkill(p,'knight',n.id,1,20,true),null);/* slot three is locked at every level now; moving it to slot two is fine */assert.equal(p.loadouts.knight.filter(Boolean).length,1);
assert.deepEqual([0,1,7,8,15,16,20,99].map(slotsAt),[2,2,2,2,2,2,2,2]);   /* TWO SLOTS AT EVERY LEVEL (Daniel 2026-09-23: four made the HUD too messy) */for(const h of HERO_IDS)for(let lv=0;lv<30;lv++){assert(growthAt(h,lv+1).hp>growthAt(h,lv).hp);assert(growthAt(h,lv+1).stamina>growthAt(h,lv).stamina);}
console.log('Progression: all 181 node destinations, 36 legacy hero/version fixtures, exact refunds, preserved ownership, backups, rollback, corrupt saves, import idempotence and loadout gates pass.');
