// Frozen legacy node mapping, including historical costs and ranks.
export const LEGACY_NODES = [
  {
    "id": "thirdCut",
    "hero": "knight",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "THIRD CUT",
    "max": 1,
    "desc": "the third cut of a run already throws: with this it throws them further and cuts a quarter harder",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "heavy",
    "hero": "knight",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "HEAVY CUT",
    "max": 2,
    "desc": "you already have it: HOLD the swing and let go to bring the sword down. held longer it breaks a guard, longer still it floors them. harder and quicker a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "baseline",
    "level": 1,
    "price": 60
  },
  {
    "id": "riposte",
    "hero": "knight",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "RIPOSTE",
    "max": 1,
    "desc": "turn a blow on the shield and your next swing, within a breath, cuts twice as hard",
    "parent": "thirdCut",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "risingCut",
    "hero": "knight",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "RISING CUT",
    "max": 1,
    "desc": "an upward cut that carries the first foe up with you and holds it in the air for your cuts",
    "parent": "thirdCut",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 3,
    "price": 100
  },
  {
    "id": "sunder",
    "hero": "knight",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "SUNDER",
    "max": 1,
    "desc": "whatever the heavy cut lands on takes the next blow twice as hard",
    "parent": "heavy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "bleed",
    "hero": "knight",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "OPEN WOUND",
    "max": 1,
    "desc": "a cut leaves a wound that bleeds: while equipped every half second, for three seconds",
    "parent": "riposte",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "lunge",
    "hero": "knight",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "LUNGE",
    "max": 1,
    "desc": "a dashing thrust through everything in front of you. nothing touches you while you go",
    "parent": "risingCut",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 7,
    "price": 190
  },
  {
    "id": "execute",
    "hero": "knight",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "EXECUTION",
    "max": 1,
    "desc": "the heavy cut or a third cut finishes any foe already under a quarter of its health",
    "parent": "sunder",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "flurry",
    "hero": "knight",
    "branch": 0,
    "row": 3,
    "col": 0,
    "name": "FLURRY",
    "max": 1,
    "desc": "swings cost half the stamina",
    "parent": "bleed",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "unbroken",
    "hero": "knight",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "UNBROKEN",
    "max": 1,
    "desc": "a run of cuts never starts over while your blows keep landing. every third cut of it is a third cut",
    "parent": "lunge",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "steady",
    "hero": "knight",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "STEADY",
    "max": 2,
    "desc": "blows on the shield cost 15% less stamina a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "plated",
    "hero": "knight",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "PLATED",
    "max": 1,
    "desc": "while it is up, the shield covers your back as well as your front",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "parry",
    "hero": "knight",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "PERFECT GUARD",
    "max": 1,
    "desc": "the perfect guard opens twice as long: raise the shield as a blow lands and it costs nothing, and whoever swung reels",
    "parent": "steady",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "shieldThrow",
    "hero": "knight",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "SHIELD THROW",
    "max": 1,
    "desc": "hurl the shield. it comes back",
    "parent": "steady",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "vengeance",
    "hero": "knight",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "VENGEANCE",
    "max": 1,
    "desc": "what the shield turns is kept, and your next swing carries it (up to 30)",
    "parent": "plated",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "bash",
    "hero": "knight",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "BULL RUSH",
    "max": 1,
    "desc": "THE LAST CHARGE runs four tiles further and what it strikes staggers twice as long. it knocks back what flies at you",
    "parent": "parry",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "warCry",
    "hero": "knight",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "WAR CRY",
    "max": 1,
    "desc": "a shout that throws back and staggers what is near, gives back 30 stamina, and for four seconds every blow on you lands a quarter lighter",
    "parent": "shieldThrow",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "bulwark",
    "hero": "knight",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "BULWARK",
    "max": 1,
    "desc": "arrows, seeds and spells that hit your shield fly back where they came from",
    "parent": "vengeance",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "holdLine",
    "hero": "knight",
    "branch": 1,
    "row": 3,
    "col": 0,
    "name": "STEADY ARM",
    "max": 1,
    "desc": "holding the shield up costs no wind: only what lands on it does",
    "parent": "bash",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "counterstroke",
    "hero": "knight",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "COUNTERSTROKE",
    "max": 1,
    "desc": "a perfect guard strikes back by itself: a quick cut at whoever swung, at full swing damage",
    "parent": "warCry",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "momentum",
    "hero": "knight",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "MOMENTUM",
    "max": 2,
    "desc": "run a second without stopping and the next blow lands 12% harder while equipped",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "bounding",
    "hero": "knight",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "BOUNDING",
    "max": 1,
    "desc": "each pogo in a row without landing hits a quarter harder, up to double, and gives back 8 stamina",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "evasion",
    "hero": "knight",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "EVASION",
    "max": 1,
    "desc": "a dodge through a blow gives back 20 stamina and makes the next swing a third cut",
    "parent": "momentum",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "groundSlam",
    "hero": "knight",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "GROUND SLAM",
    "max": 1,
    "desc": "quake the floor both ways",
    "parent": "momentum",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 5,
    "price": 140
  },
  {
    "id": "airRoll",
    "hero": "knight",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "AIR ROLL",
    "max": 1,
    "desc": "dodge once in the air, every jump",
    "parent": "bounding",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "lightStep",
    "hero": "knight",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "LIGHT STEP",
    "max": 1,
    "desc": "dodges cost three less stamina; a swung attack still has to finish",
    "parent": "evasion",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "whirlwind",
    "hero": "knight",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "WHIRLWIND",
    "max": 1,
    "desc": "spin with the blade out: two cuts at everything around you",
    "parent": "groundSlam",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 9,
    "price": 240
  },
  {
    "id": "hangCut",
    "hero": "knight",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "HANGING CUT",
    "max": 1,
    "desc": "every swing in a jump holds you in the air, not only the first",
    "parent": "airRoll",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "airDash",
    "hero": "knight",
    "branch": 2,
    "row": 3,
    "col": 2,
    "name": "SLIPSTREAM",
    "max": 1,
    "desc": "dash twice before you land",
    "parent": "hangCut",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "endlessSky",
    "hero": "knight",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "ENDLESS SKY",
    "max": 1,
    "desc": "a plunge that lands a hit gives back your air roll and your jump: one more jump, from the air",
    "parent": "whirlwind",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "skip",
    "hero": "pyro",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "SKIPPING EMBER",
    "max": 1,
    "desc": "an ember that hits the ground bounces once, and burns where it lands",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "stoke",
    "hero": "pyro",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "STOKE",
    "max": 1,
    "desc": "an ember that finds a foe already burning gives back half its price in wind, and heat with it",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "twin",
    "hero": "pyro",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "TWIN EMBER",
    "max": 1,
    "desc": "a tap throws two embers, one high and one low",
    "parent": "skip",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "vent",
    "hero": "pyro",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "VENT",
    "max": 1,
    "desc": "blast all your heat out at once. the hotter, the harder. lights lamps",
    "parent": "skip",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "scatter",
    "hero": "pyro",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "SCATTER",
    "max": 1,
    "desc": "an ember bursts where it strikes: 6 damage to everything else near it",
    "parent": "stoke",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "brand",
    "hero": "pyro",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "BRAND",
    "max": 1,
    "desc": "a burning foe takes half as much again from everything",
    "parent": "twin",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "meteor",
    "hero": "pyro",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "METEOR",
    "max": 1,
    "desc": "call fire out of the sky onto the nearest foe ahead. the hotter you run, the harder it lands",
    "parent": "vent",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "conflagration",
    "hero": "pyro",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "CONFLAGRATION",
    "max": 1,
    "desc": "a burning foe that dies sets light to whatever stands near it",
    "parent": "scatter",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "sunder",
    "hero": "pyro",
    "branch": 0,
    "row": 3,
    "col": 0,
    "name": "SCORCHED EARTH",
    "max": 1,
    "desc": "the bellows (the held flame) leaves the ground burning where its cone passed",
    "parent": "brand",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "wildfire",
    "hero": "pyro",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "WILDFIRE",
    "max": 1,
    "desc": "an ember that hits a burning foe leaps on to the nearest other burning foe, once an ember",
    "parent": "meteor",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "longFlame",
    "hero": "pyro",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "LONG FLAME",
    "max": 2,
    "desc": "the jet reaches 11% further while equipped",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "pilot",
    "hero": "pyro",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "PILOT LIGHT",
    "max": 1,
    "desc": "your heat never burns down below a third",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "updraft",
    "hero": "pyro",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "UPDRAFT",
    "max": 1,
    "desc": "the jet lights in the air too, and holds you up: you fall slowly for as long as it burns",
    "parent": "longFlame",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "wisp",
    "hero": "pyro",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "WISP",
    "max": 1,
    "desc": "a flame that follows you, lights every lamp it passes and dives at foes",
    "parent": "longFlame",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "searing",
    "hero": "pyro",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "SEARING",
    "max": 1,
    "desc": "what the jet touches burns three times as long",
    "parent": "pilot",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "jetWalk",
    "hero": "pyro",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "WALKING FLAME",
    "max": 1,
    "desc": "you can walk, slowly, while the jet burns",
    "parent": "updraft",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "flameRing",
    "hero": "pyro",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "RING OF FIRE",
    "max": 1,
    "desc": "a ring of flame rolls out from you, burning and throwing back what it passes and eating what flies at you",
    "parent": "wisp",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "blaze",
    "hero": "pyro",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "BLAZE",
    "max": 1,
    "desc": "full heat holds twice as long before it starts to go",
    "parent": "searing",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "backdraft",
    "hero": "pyro",
    "branch": 1,
    "row": 3,
    "col": 2,
    "name": "BACKDRAFT",
    "max": 1,
    "desc": "coming to full heat throws a ring of flame off you",
    "parent": "blaze",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "inferno",
    "hero": "pyro",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "INFERNO",
    "max": 1,
    "desc": "full heat is a six-second INFERNO: the jet never goes out, reaches further and burns hotter. then the heat is gone",
    "parent": "flameRing",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "ashCloak",
    "hero": "pyro",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "ASH CLOAK",
    "max": 2,
    "desc": "for a moment after a dodge, blows land 12% lighter a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "emberSkin",
    "hero": "pyro",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "EMBER SKIN",
    "max": 1,
    "desc": "whatever strikes you catches fire",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "kindle",
    "hero": "pyro",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "KINDLE",
    "max": 1,
    "desc": "fire mends you instead of burning you. stand in it",
    "parent": "ashCloak",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "fireWall",
    "hero": "pyro",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "FIRE WALL",
    "max": 1,
    "desc": "a line of flame ahead of you for three seconds",
    "parent": "ashCloak",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "heatShield",
    "hero": "pyro",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "HEAT SHIELD",
    "max": 1,
    "desc": "above half heat you take a quarter less damage",
    "parent": "emberSkin",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "smoulder",
    "hero": "pyro",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "SMOULDER",
    "max": 1,
    "desc": "standing in fire, anyone's fire, fills your heat",
    "parent": "kindle",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "cinderStep",
    "hero": "pyro",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "CINDER STEP",
    "max": 1,
    "desc": "a burning dash you cannot be hit in",
    "parent": "fireWall",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "emberHeart",
    "hero": "pyro",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "EMBER HEART",
    "max": 1,
    "desc": "under a third of your health everything you do hits half as hard again",
    "parent": "heatShield",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "phoenix",
    "hero": "pyro",
    "branch": 2,
    "row": 3,
    "col": 0,
    "name": "PHOENIX",
    "max": 1,
    "desc": "once a wood, a killing blow leaves you on your feet in a burst of fire",
    "parent": "smoulder",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "phoenixTrail",
    "hero": "pyro",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "PHOENIX TRAIL",
    "max": 1,
    "desc": "PHOENIX is yours and comes back at every shrine and every life, and every dodge leaves a trail of fire",
    "parent": "cinderStep",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "radiance",
    "hero": "paladin",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "RADIANCE",
    "max": 2,
    "desc": "the light fills 10% faster a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "litany",
    "hero": "paladin",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "LITANY",
    "max": 1,
    "desc": "mend no longer roots you: heal on the move",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "mercy",
    "hero": "paladin",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "MERCY",
    "max": 1,
    "desc": "mend gives back 30 stamina as well",
    "parent": "radiance",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "consecrate",
    "hero": "paladin",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "CONSECRATE",
    "max": 1,
    "desc": "hallow the ground around you. foes on it burn with holy fire, and you mend while you stand in it",
    "parent": "radiance",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "zeal",
    "hero": "paladin",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "ZEAL",
    "max": 1,
    "desc": "every foe judgement strikes gives you back 8 health",
    "parent": "litany",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "smite",
    "hero": "paladin",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "SMITE",
    "max": 1,
    "desc": "judgement leaves every foe it strikes burning",
    "parent": "mercy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "lightLance",
    "hero": "paladin",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "SPEAR OF LIGHT",
    "max": 1,
    "desc": "a lance of light straight ahead, through everything in its path to the first wall",
    "parent": "consecrate",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "beacon",
    "hero": "paladin",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "BEACON",
    "max": 1,
    "desc": "while the light is full you burn: foes near you catch fire",
    "parent": "zeal",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "martyr",
    "hero": "paladin",
    "branch": 0,
    "row": 3,
    "col": 0,
    "name": "MARTYR",
    "max": 1,
    "desc": "once a life, falling under a quarter health fills the light at once",
    "parent": "smite",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "doubleJudge",
    "hero": "paladin",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "DOUBLE JUDGEMENT",
    "max": 1,
    "desc": "judgement strikes twice: a second fall of light a beat after the first",
    "parent": "lightLance",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "stalwart",
    "hero": "paladin",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "STALWART",
    "max": 2,
    "desc": "the aegis drains 15% less stamina a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "warded",
    "hero": "paladin",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "WARDED",
    "max": 1,
    "desc": "the aegis covers your back as well as your front",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "reflect",
    "hero": "paladin",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "REFLECTION",
    "max": 1,
    "desc": "arrows, seeds and spells the aegis turns fly back where they came from",
    "parent": "stalwart",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "holyCharge",
    "hero": "paladin",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "HOLY CHARGE",
    "max": 1,
    "desc": "charge shield-first. whatever you hit is thrown aside and reels, and nothing touches you while you go",
    "parent": "stalwart",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "unwavering",
    "hero": "paladin",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "UNWAVERING",
    "max": 1,
    "desc": "the aegis holds for as long as you have the wind for it, not a breath and a half",
    "parent": "warded",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "retribution",
    "hero": "paladin",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "RETRIBUTION",
    "max": 1,
    "desc": "whoever lands a blow on the aegis reels from it",
    "parent": "reflect",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "divineShield",
    "hero": "paladin",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "DIVINE SHIELD",
    "max": 1,
    "desc": "a ward of light all round you: nothing touches you for two seconds",
    "parent": "holyCharge",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "crusade",
    "hero": "paladin",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "CRUSADE",
    "max": 1,
    "desc": "dropping the aegis throws back and staggers everything near you",
    "parent": "unwavering",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "sanctuary",
    "hero": "paladin",
    "branch": 1,
    "row": 3,
    "col": 0,
    "name": "SANCTUARY",
    "max": 1,
    "desc": "while you hold the aegis you mend, 3 health a second",
    "parent": "retribution",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "fortress",
    "hero": "paladin",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "MOVING FORTRESS",
    "max": 1,
    "desc": "walk at full pace behind the aegis, and raise it as a blow lands to PARRY: whoever swung reels",
    "parent": "divineShield",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "heavy",
    "hero": "paladin",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "OVERHEAD",
    "max": 2,
    "desc": "you already have it: HOLD the maul and the ground carries the blow both ways. 15% harder and quicker to wind up a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "baseline",
    "level": 1,
    "price": 60
  },
  {
    "id": "shockwave",
    "hero": "paladin",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "SHOCKWAVE",
    "max": 1,
    "desc": "hammerfall waves travel twice as far",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "sunder",
    "hero": "paladin",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "SHATTER",
    "max": 1,
    "desc": "everything the overhead's waves pass is staggered",
    "parent": "heavy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "blessedHammer",
    "hero": "paladin",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "BLESSED HAMMER",
    "max": 1,
    "desc": "a hammer of light that spins out from you in a widening spiral, striking all it passes",
    "parent": "heavy",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "heavyTread",
    "hero": "paladin",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "HEAVY TREAD",
    "max": 1,
    "desc": "the shoulder dash sends a quake rolling on ahead of you",
    "parent": "shockwave",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "concuss",
    "hero": "paladin",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "CONCUSSION",
    "max": 1,
    "desc": "the third maul blow in a run leaves ANY foe reeling, not only a small one",
    "parent": "sunder",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "hammerLeap",
    "hero": "paladin",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "HAMMER LEAP",
    "max": 1,
    "desc": "leap and bring the maul down: the ground carries it both ways",
    "parent": "blessedHammer",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "earthshaker",
    "hero": "paladin",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "EARTHSHAKER",
    "max": 1,
    "desc": "land hard from a height and the ground quakes both ways",
    "parent": "heavyTread",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "wrath",
    "hero": "paladin",
    "branch": 2,
    "row": 3,
    "col": 0,
    "name": "WRATH",
    "max": 1,
    "desc": "every kill fills a tenth of the light",
    "parent": "concuss",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "aftershock",
    "hero": "paladin",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "AFTERSHOCK",
    "max": 1,
    "desc": "every third maul blow in a run quakes the ground both ways",
    "parent": "hammerLeap",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "heavy",
    "hero": "pirate",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "THE PISTOL",
    "max": 2,
    "desc": "you already have it: HOLD the swing and he levels it. nothing blocks a ball, and then it is EMPTY until gold reaches him. 15% harder and quicker a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "baseline",
    "level": 1,
    "price": 60
  },
  {
    "id": "longBarrel",
    "hero": "pirate",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "LONG BARREL",
    "max": 1,
    "desc": "the pistol carries twice as far",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "powderBurn",
    "hero": "pirate",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "POWDER BURN",
    "max": 1,
    "desc": "whatever the ball strikes is left burning",
    "parent": "heavy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "grapeshot",
    "hero": "pirate",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "GRAPESHOT",
    "max": 1,
    "desc": "a scatter charge. a cone of shot hits everything in front of you, and is spent whether it finds anything or not",
    "parent": "heavy",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "quickHands",
    "hero": "pirate",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "QUICK HANDS",
    "max": 1,
    "desc": "level the pistol in the air and out of a roll, not only standing",
    "parent": "longBarrel",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "deadEye",
    "hero": "pirate",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "DEAD EYE",
    "max": 1,
    "desc": "a ball into anything already staggered lands twice as hard",
    "parent": "powderBurn",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "broadside",
    "hero": "pirate",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "BROADSIDE",
    "max": 1,
    "desc": "he empties everything he has straight down the deck, through everything standing in the line of it",
    "parent": "grapeshot",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "sunder",
    "hero": "pirate",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "HOLED",
    "max": 1,
    "desc": "whatever the ball goes through takes the next blow twice as hard",
    "parent": "quickHands",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "secondBarrel",
    "hero": "pirate",
    "branch": 0,
    "row": 3,
    "col": 0,
    "name": "SECOND BARREL",
    "max": 1,
    "desc": "he carries two: the pistol fires twice before it is empty",
    "parent": "deadEye",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "hotBarrel",
    "hero": "pirate",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "HOT BARREL",
    "max": 1,
    "desc": "a kill fills every barrel, whatever did the killing, and for three seconds the pistol comes up with no wind-up",
    "parent": "broadside",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "deepPockets",
    "hero": "pirate",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "DEEP POCKETS",
    "max": 2,
    "desc": "every coin is worth a third more to the purse while equipped",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "greased",
    "hero": "pirate",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "GREASED PALM",
    "max": 1,
    "desc": "every coin you pick up gives back 6 wind",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "looter",
    "hero": "pirate",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "LOOTER",
    "max": 1,
    "desc": "anything you put down with the blade shakes gold loose",
    "parent": "deepPockets",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "rum",
    "hero": "pirate",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "RUM",
    "max": 1,
    "desc": "a swig from the bottle. it mends you and then makes you reckless: harder blows and a longer roll for four seconds, and you take a quarter more",
    "parent": "deepPockets",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "shareOut",
    "hero": "pirate",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "FAIR SHARES",
    "max": 1,
    "desc": "every coin mends 2 health",
    "parent": "greased",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "ransom",
    "hero": "pirate",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "RANSOM",
    "max": 1,
    "desc": "the black flag gives back half your wind as well",
    "parent": "looter",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "blackSpot",
    "hero": "pirate",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "THE BLACK SPOT",
    "max": 1,
    "desc": "put it in a foe's hand. it takes a third more damage for eight seconds and pays double if defeated while marked",
    "parent": "rum",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "pieces",
    "hero": "pirate",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "PIECES OF EIGHT",
    "max": 1,
    "desc": "every eighth coin of a run is worth ten",
    "parent": "shareOut",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "noQuarter",
    "hero": "pirate",
    "branch": 1,
    "row": 3,
    "col": 0,
    "name": "NO QUARTER",
    "max": 1,
    "desc": "every kill puts 10 in the purse",
    "parent": "ransom",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "paidInGold",
    "hero": "pirate",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "PAID IN GOLD",
    "max": 1,
    "desc": "a skill still waiting fires anyway for 15 gold, and every coin picked up takes a third of a second off every wait",
    "parent": "blackSpot",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "longLine",
    "hero": "pirate",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "LONG LINE",
    "max": 2,
    "desc": "the hook reaches a tile further and hauls harder while equipped",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "cutthroat",
    "hero": "pirate",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "CUTTHROAT",
    "max": 1,
    "desc": "the fifth blow of a quick run lands twice as hard",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "haulCut",
    "hero": "pirate",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "HAUL AND CUT",
    "max": 1,
    "desc": "a foe the hook hauls in arrives as the fourth blow of your run: the next cut is the fifth",
    "parent": "longLine",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "boarding",
    "hero": "pirate",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "BOARDING PARTY",
    "max": 1,
    "desc": "hook and haul yourself forward through anything in the way, cutting as you pass",
    "parent": "longLine",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "turncoat",
    "hero": "pirate",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "TURNCOAT",
    "max": 1,
    "desc": "a turned blow makes your next cutlass blow twice as hard",
    "parent": "cutthroat",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "swash",
    "hero": "pirate",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "SWASHBUCKLE",
    "max": 1,
    "desc": "roll once in the air, every jump",
    "parent": "haulCut",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "keelhaul",
    "hero": "pirate",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "KEELHAUL",
    "max": 1,
    "desc": "the hook goes out, takes whatever is in front of him, and drags it PAST him. it lands on its back behind you",
    "parent": "boarding",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "runThrough",
    "hero": "pirate",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "RUN THROUGH",
    "max": 1,
    "desc": "the fifth blow of a run goes through a raised guard as though it were not there",
    "parent": "turncoat",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "rollCut",
    "hero": "pirate",
    "branch": 2,
    "row": 3,
    "col": 0,
    "name": "TUMBLING CUT",
    "max": 1,
    "desc": "a swing out of a roll is a dash attack: it carries you on and throws what it hits",
    "parent": "swash",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "parryCut",
    "hero": "pirate",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "RIPOSTE",
    "max": 1,
    "desc": "turning a blow with the cutlass strikes back by itself, at full swing damage",
    "parent": "keelhaul",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "heavy",
    "hero": "reaper",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "THE PLANTED BLADE",
    "max": 2,
    "desc": "you already have it: HOLD the swing and he drives the greatsword into the ground; bolts of blood burst out in a fan, through any guard, marking and bleeding. 10% harder a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "baseline",
    "level": 1,
    "price": 60
  },
  {
    "id": "longHaft",
    "hero": "reaper",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "LONG REACH",
    "max": 1,
    "desc": "the cleave and the planted blade reach most of a tile further",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "sunder",
    "hero": "reaper",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "OPENED",
    "max": 1,
    "desc": "whatever the blood bolts land on takes the next blow twice as hard",
    "parent": "heavy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "harvestMoon",
    "hero": "reaper",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "BLOOD BOIL",
    "max": 1,
    "desc": "the ground where he stands boils with blood, and anything that walks through it burns, over and over, for three seconds",
    "parent": "heavy",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "bloodMark",
    "hero": "reaper",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "MARKED IN BLOOD",
    "max": 1,
    "desc": "the cleave marks whatever it cuts",
    "parent": "longHaft",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "fullCircle",
    "hero": "reaper",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "THE SECOND VOLLEY",
    "max": 1,
    "desc": "the planted blade looses a second volley of blood bolts",
    "parent": "sunder",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "graveTide",
    "hero": "reaper",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "GRAVE TIDE",
    "max": 1,
    "desc": "hands come up out of the floor ahead of you, holding and tearing at whatever is standing on it",
    "parent": "harvestMoon",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "rend",
    "hero": "reaper",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "REND",
    "max": 1,
    "desc": "anything wearing your mark bleeds when the blade finds it",
    "parent": "bloodMark",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "coldComfort",
    "hero": "reaper",
    "branch": 0,
    "row": 3,
    "col": 2,
    "name": "COLD COMFORT",
    "max": 1,
    "desc": "while SUMMON SKELETON is waiting and no skeleton of yours is standing, the greatsword cuts half as hard again",
    "parent": "rend",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "winnow",
    "hero": "reaper",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "WINNOWED",
    "max": 1,
    "desc": "a marked foe under a quarter of its health dies to the next thing you do to it, whatever that is",
    "parent": "graveTide",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "summonSkeleton",
    "hero": "reaper",
    "branch": 1,
    "row": 0,
    "col": 1,
    "name": "SUMMON SKELETON",
    "max": 1,
    "desc": "a skeleton stands up beside him - a warrior, an archer or a mage, at random - and fights for ten seconds. one at a time, and eighteen seconds between",
    "parent": null,
    "active": true,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "graveGoods",
    "hero": "reaper",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "GRAVE GOODS",
    "max": 2,
    "desc": "your skeletons last three seconds longer, hit two harder and hold together for one more blow a point",
    "parent": "summonSkeleton",
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "gleaner",
    "hero": "reaper",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "GLEANER",
    "max": 1,
    "desc": "SUMMON SKELETON waits a third less: twelve seconds, not eighteen",
    "parent": "summonSkeleton",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "press",
    "hero": "reaper",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "THE PRESS",
    "max": 1,
    "desc": "SUMMON SKELETON stands up two at once, of two kinds, and two can be standing",
    "parent": "graveGoods",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "unholyGround",
    "hero": "reaper",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "UNHOLY GROUND",
    "max": 1,
    "desc": "a patch of floor that is his. theirs standing in it are marked and bleed; yours stop running out of time and put a bone back",
    "parent": "graveGoods",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "bidden",
    "hero": "reaper",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "BIDDEN",
    "max": 1,
    "desc": "what you summon goes for whatever you struck last",
    "parent": "gleaner",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "ossuary",
    "hero": "reaper",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "OSSUARY",
    "max": 1,
    "desc": "a skeleton of yours that comes apart, broken or out of time, takes four seconds off SUMMON SKELETON's wait",
    "parent": "press",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "gravecall",
    "hero": "reaper",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "GRAVECALL",
    "max": 1,
    "desc": "one of each kind stands up round him at once - a warrior, an archer and a mage - for five seconds. they do not count against SUMMON SKELETON's one",
    "parent": "unholyGround",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "dueRites",
    "hero": "reaper",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "DUE RITES",
    "max": 1,
    "desc": "a kill inside the reach of a full nova leaves a heart behind",
    "parent": "bidden",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "secondDeath",
    "hero": "reaper",
    "branch": 1,
    "row": 3,
    "col": 0,
    "name": "SECOND DEATH",
    "max": 1,
    "desc": "a skeleton that comes apart - broken or out of time - takes what is near it with it",
    "parent": "ossuary",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "graveProvides",
    "hero": "reaper",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "THE GRAVE PROVIDES",
    "max": 1,
    "desc": "a kill, while you have room for a skeleton, is a free summon: one stands up where the body fell, the kind the body was",
    "parent": "gravecall",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "deathwatch",
    "hero": "reaper",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "WIDE WARD",
    "max": 2,
    "desc": "the ward holds a fifth more a point before it breaks, so a full nova reaches further and hits harder",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "drainWalk",
    "hero": "reaper",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "WARD WALK",
    "max": 1,
    "desc": "you can walk while the ward is up, slowly: the blade comes with you",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "longPassing",
    "hero": "reaper",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "LONG PASSING",
    "max": 1,
    "desc": "the passing goes half again as far, and marks everything it goes through",
    "parent": "deathwatch",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "scytheThrown",
    "hero": "reaper",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "DEATH COIL",
    "max": 1,
    "desc": "a knot of blood goes out until it finds something, opens it, marks it, and comes back into him as health",
    "parent": "deathwatch",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "wardPull",
    "hero": "reaper",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "THE PULL",
    "max": 1,
    "desc": "the nova drags what it catches a step toward him",
    "parent": "drainWalk",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "lastRites",
    "hero": "reaper",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "LAST RITES",
    "max": 1,
    "desc": "blood surge takes six more from each of them, reaches further and holds them half a second longer",
    "parent": "longPassing",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "deathGrip",
    "hero": "reaper",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "DEATH GRIP",
    "max": 1,
    "desc": "the rune goes out, takes the nearest thing in front of him and DRAGS IT TO HIS FEET, marked and off balance. a boss will not come, but it wears the mark",
    "parent": "scytheThrown",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "deepRed",
    "hero": "reaper",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "DEEP RED",
    "max": 1,
    "desc": "the nova heals half again as much, and four more for every marked foe it catches",
    "parent": "wardPull",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "gripAll",
    "hero": "reaper",
    "branch": 2,
    "row": 3,
    "col": 0,
    "name": "THE WHOLE ROW",
    "max": 1,
    "desc": "DEATH GRIP takes the whole line in front of him instead of the nearest thing. all of it arrives at once",
    "parent": "deathGrip",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "overflow",
    "hero": "reaper",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "OVERFLOW",
    "max": 1,
    "desc": "a FULL ward bursts twice: a second nova goes out a beat after the first",
    "parent": "deathGrip",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "keenPoint",
    "hero": "warden",
    "branch": 0,
    "row": 0,
    "col": 0,
    "name": "KEEN POINT",
    "max": 1,
    "desc": "the point pays from four pixels further back: more of the shaft counts as the tip",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "heavy",
    "hero": "warden",
    "branch": 0,
    "row": 0,
    "col": 2,
    "name": "THE RUN-THROUGH",
    "max": 2,
    "desc": "you already have it: HOLD the thrust to wind it, let go and she lunges through a whole line. 15% harder and quicker to wind a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "baseline",
    "level": 1,
    "price": 60
  },
  {
    "id": "throughAndThrough",
    "hero": "warden",
    "branch": 0,
    "row": 1,
    "col": 0,
    "name": "THROUGH AND THROUGH",
    "max": 1,
    "desc": "the run-through reaches a tile further down the line",
    "parent": "keenPoint",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "skewer",
    "hero": "warden",
    "branch": 0,
    "row": 1,
    "col": 1,
    "name": "SKEWER",
    "max": 1,
    "desc": "a driven thrust that PINS the first thing it catches to the ground",
    "parent": "keenPoint",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "openPoint",
    "hero": "warden",
    "branch": 0,
    "row": 1,
    "col": 2,
    "name": "OPENED",
    "max": 1,
    "desc": "whatever the run-through skewers takes the next blow twice as hard",
    "parent": "heavy",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "ringing",
    "hero": "warden",
    "branch": 0,
    "row": 2,
    "col": 0,
    "name": "RINGING",
    "max": 1,
    "desc": "a tip hit pays double VIGIL and rocks what it lands on",
    "parent": "throughAndThrough",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "driveHome",
    "hero": "warden",
    "branch": 0,
    "row": 2,
    "col": 1,
    "name": "DRIVE HOME",
    "max": 1,
    "desc": "the run-through throws the first one down the line hard enough to slam it into a wall",
    "parent": "skewer",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "exact",
    "hero": "warden",
    "branch": 0,
    "row": 2,
    "col": 2,
    "name": "EXACTNESS",
    "max": 1,
    "desc": "a tip hit on something winding up takes the blow off it",
    "parent": "openPoint",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "deepSet",
    "hero": "warden",
    "branch": 0,
    "row": 3,
    "col": 0,
    "name": "DEEP SET",
    "max": 1,
    "desc": "the further out the point lands, the harder it bites: up to a fifth more at full stretch",
    "parent": "ringing",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "spearhead",
    "hero": "warden",
    "branch": 0,
    "row": 3,
    "col": 1,
    "name": "SPEARHEAD",
    "max": 1,
    "desc": "every third thrust of a run IS a run-through, with no winding up at all",
    "parent": "driveHome",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "quickShaft",
    "hero": "warden",
    "branch": 1,
    "row": 0,
    "col": 0,
    "name": "QUICK SHAFT",
    "max": 2,
    "desc": "the sweep costs a fifth less wind a point, and she is out of it a fifth sooner",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "wideGuard",
    "hero": "warden",
    "branch": 1,
    "row": 0,
    "col": 2,
    "name": "WIDE GUARD",
    "max": 1,
    "desc": "the sweep covers higher and reaches further out, and the point catches a charge coming in off her level",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "standFast",
    "hero": "warden",
    "branch": 1,
    "row": 1,
    "col": 0,
    "name": "STAND FAST",
    "max": 1,
    "desc": "a blow turned on the shaft pays double VIGIL, and what threw it is left reeling half again as long",
    "parent": "quickShaft",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "setSpears",
    "hero": "warden",
    "branch": 1,
    "row": 1,
    "col": 1,
    "name": "SET THE SPEARS",
    "max": 1,
    "desc": "plant three spears in the ground right in front of her, and they pin",
    "parent": "quickShaft",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 5,
    "price": 140
  },
  {
    "id": "sendBack",
    "hero": "warden",
    "branch": 1,
    "row": 1,
    "col": 2,
    "name": "SEND IT BACK",
    "max": 1,
    "desc": "an arrow or a thrown thing swatted out of the air goes back the way it came, at whoever threw it",
    "parent": "wideGuard",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "counterpoise",
    "hero": "warden",
    "branch": 1,
    "row": 2,
    "col": 0,
    "name": "COUNTERPOISE",
    "max": 1,
    "desc": "the blow she turns leaves the one that threw it OPENED: the next blow on it lands twice as hard",
    "parent": "standFast",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "widerRow",
    "hero": "warden",
    "branch": 1,
    "row": 2,
    "col": 1,
    "name": "A WIDER ROW",
    "max": 1,
    "desc": "the phalanx sets its spears closer together and carries them further across the room",
    "parent": "setSpears",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "everReady",
    "hero": "warden",
    "branch": 1,
    "row": 2,
    "col": 2,
    "name": "EVER READY",
    "max": 1,
    "desc": "a sweep that TURNS something is back in her hands at once: no recovery on it at all",
    "parent": "sendBack",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "spitted",
    "hero": "warden",
    "branch": 1,
    "row": 3,
    "col": 0,
    "name": "SPITTED",
    "max": 1,
    "desc": "a charge that runs onto her point is HELD on it as well as broken, the way her plunge holds one",
    "parent": "counterpoise",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "holdTheLine",
    "hero": "warden",
    "branch": 1,
    "row": 3,
    "col": 1,
    "name": "HEDGE OF SPEARS",
    "max": 1,
    "desc": "the phalanx STAYS UP: a standing wall of spears for three seconds, and what walks into it is pinned again",
    "parent": "widerRow",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "lightFoot",
    "hero": "warden",
    "branch": 2,
    "row": 0,
    "col": 0,
    "name": "LIGHT FOOT",
    "max": 2,
    "desc": "the hop back carries her 15% further a point",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 1,
    "destination": "growth",
    "level": 1,
    "price": 60
  },
  {
    "id": "vaulter",
    "hero": "warden",
    "branch": 2,
    "row": 0,
    "col": 2,
    "name": "VAULTER",
    "max": 1,
    "desc": "the pole vault needs no dash and no wind: plant it and go",
    "parent": null,
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 1,
    "price": 60
  },
  {
    "id": "giveGround",
    "hero": "warden",
    "branch": 2,
    "row": 1,
    "col": 0,
    "name": "GIVE GROUND",
    "max": 1,
    "desc": "the hop back staggers whatever had got inside the spear",
    "parent": "lightFoot",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "harrier",
    "hero": "warden",
    "branch": 2,
    "row": 1,
    "col": 1,
    "name": "HARRIER",
    "max": 1,
    "desc": "vault clean over the nearest foe and come down behind it, point first",
    "parent": "lightFoot",
    "active": true,
    "cap": false,
    "cost": 3,
    "destination": "skill",
    "level": 3,
    "price": 100
  },
  {
    "id": "longVault",
    "hero": "warden",
    "branch": 2,
    "row": 1,
    "col": 2,
    "name": "LONG VAULT",
    "max": 1,
    "desc": "the vault carries a tile and a half further, and she can thrust out of it",
    "parent": "vaulter",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 4,
    "price": 120
  },
  {
    "id": "pinTwist",
    "hero": "warden",
    "branch": 2,
    "row": 2,
    "col": 0,
    "name": "TWIST IT",
    "max": 1,
    "desc": "every stab into something pinned leaves it bleeding",
    "parent": "giveGround",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "freeHand",
    "hero": "warden",
    "branch": 2,
    "row": 2,
    "col": 1,
    "name": "FREE HAND",
    "max": 1,
    "desc": "pulling free of a pin costs no recovery at all, and hands back 20 wind",
    "parent": "harrier",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "airPoint",
    "hero": "warden",
    "branch": 2,
    "row": 2,
    "col": 2,
    "name": "AIR POINT",
    "max": 1,
    "desc": "leaving a pin hands back her jump and her dash: a pin is somewhere to go FROM",
    "parent": "longVault",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 8,
    "price": 220
  },
  {
    "id": "holdThem",
    "hero": "warden",
    "branch": 2,
    "row": 3,
    "col": 0,
    "name": "HOLD THEM DOWN",
    "max": 1,
    "desc": "a pin holds half again as long and she gets a fourth stab into it",
    "parent": "pinTwist",
    "active": false,
    "cap": false,
    "cost": 2,
    "destination": "skill",
    "level": 12,
    "price": 360
  },
  {
    "id": "skirmisher",
    "hero": "warden",
    "branch": 2,
    "row": 3,
    "col": 1,
    "name": "SKIRMISHER",
    "max": 1,
    "desc": "pull free and she HURLS the body off the point at whatever is nearest, and both of them go down",
    "parent": "freeHand",
    "active": false,
    "cap": true,
    "cost": 4,
    "destination": "skill",
    "level": 12,
    "price": 360
  }
];
/* THE STARTER KITS' NEW ACTIVES (2026-09-23): bought abilities that were never talents, so they are kept out of the frozen
   historical mapping above (a save from before them has nothing to migrate) and joined onto what the shop sells. Their
   level and price follow the one ladder (tools/talents.mjs PRICE_AT). */
export const STARTER_SKILLS = [
  { "id": "disarm", "hero": "knight", "branch": 0, "row": 4, "col": 1, "name": "DISARM", "max": 1, "desc": "a hooking cut that strips a foe of its shield or its weapon for the rest of the fight. a boss is only opened a moment", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 14, "price": 400 },
  { "id": "ironclad", "hero": "knight", "branch": 1, "row": 4, "col": 1, "name": "IRONCLAD", "max": 1, "desc": "for four seconds no blow staggers him or stops his swing. they still hurt", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 17, "price": 460 },
  { "id": "swordOfRealm", "hero": "knight", "branch": 2, "row": 4, "col": 1, "name": "SWORD OF THE REALM", "max": 1, "desc": "for ten seconds every swing sends a wave of light along the floor, and a third cut sends a great one", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 20, "price": 520 },
  { "id": "wheel", "hero": "warden", "branch": 1, "row": 4, "col": 1, "name": "THE WHEEL", "max": 1, "desc": "a low sweep of the shaft all the way round her: everything in reach goes down on its back", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 7, "price": 190 },
  { "id": "javelin", "hero": "warden", "branch": 0, "row": 4, "col": 1, "name": "JAVELIN", "max": 1, "desc": "hurl the spear: it pins the first foe to what is behind it, or sticks in a wall as a step. F again brings it back", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 9, "price": 240 },
  { "id": "poleSpring", "hero": "warden", "branch": 2, "row": 4, "col": 1, "name": "POLE SPRING", "max": 1, "desc": "plant the spear and vault straight up, then come down point first: what she lands on is pinned", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 12, "price": 360 },
  { "id": "fullStretch", "hero": "warden", "branch": 0, "row": 5, "col": 1, "name": "FULL STRETCH", "max": 1, "desc": "for five seconds the spear reaches half again as far, and every blow of it lands as the tip", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 14, "price": 400 },
  { "id": "spearDance", "hero": "warden", "branch": 0, "row": 6, "col": 1, "name": "SPEAR DANCE", "max": 1, "desc": "six quick thrusts from where she stands: each one that lands on the point rings", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 17, "price": 460 },
  { "id": "rainOfSpears", "hero": "warden", "branch": 1, "row": 6, "col": 1, "name": "RAIN OF SPEARS", "max": 1, "desc": "spears thrown at the sky come down across the room and pin what they find", "parent": null, "active": true, "cap": false, "cost": 3, "destination": "skill", "level": 20, "price": 520 },
];
export const SKILLS = LEGACY_NODES.filter(n => n.destination === 'skill').concat(STARTER_SKILLS);
